#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Route and page-type keyword mapping for Amazon recommendations."""

from typing import Dict, List, Tuple

AMAZON_THEME_POOL: List[Dict[str, object]] = [
    {
        "id": "kindle-productivity",
        "enabled": True,
        "category_label": "Kindle 仕事効率化",
        "title": "仕事効率化を学ぶKindle本",
        "query": "Kindle 仕事効率化",
        "query_variants": ["Kindle タスク管理", "Kindle 業務改善"],
        "cta": "Amazonで見る",
        "priority_page_types": ["landing", "tool_index", "guide", "info"],
        "priority_path_prefixes": ["/", "/tools", "/guide", "/faq"],
    },
    {
        "id": "kindle-excel",
        "enabled": True,
        "category_label": "Kindle Excel",
        "title": "Excel・表作業のKindle本",
        "query": "Kindle Excel",
        "query_variants": ["Kindle データ分析", "Excel 表計算 Kindle"],
        "cta": "Excel本を見る",
        "priority_page_types": ["tool", "tool_index", "guide", "article"],
        "priority_path_prefixes": ["/tools/csv", "/guide/csv", "/tools", "/blog"],
    },
    {
        "id": "kindle-seo-marketing",
        "enabled": True,
        "category_label": "Kindle SEO",
        "title": "SEO・WebマーケティングのKindle本",
        "query": "Kindle SEO",
        "query_variants": ["Kindle Webマーケティング", "SNS運用 Kindle"],
        "cta": "SEO本を見る",
        "priority_page_types": ["tool", "tool_index", "guide", "article"],
        "priority_path_prefixes": ["/tools/seo", "/guide/seo", "/blog"],
    },
    {
        "id": "kindle-writing-documents",
        "enabled": True,
        "category_label": "Kindle 文章・資料",
        "title": "文章作成・資料作成のKindle本",
        "query": "Kindle 文章術",
        "query_variants": ["資料作成 Kindle", "ビジネス文書 Kindle"],
        "cta": "資料作成本を見る",
        "priority_page_types": ["landing", "guide", "article", "info"],
        "priority_path_prefixes": ["/", "/guide", "/blog", "/glossary"],
    },
    {
        "id": "pdf-document-work",
        "enabled": True,
        "category_label": "PDF・書類作業",
        "title": "PDF・書類作業を整える仕事道具",
        "query": "PDF 書類整理 文房具",
        "query_variants": ["書類整理 文房具", "デスク整理 収納"],
        "cta": "書類作業の道具を見る",
        "priority_page_types": ["tool", "tool_index", "landing", "guide"],
        "priority_path_prefixes": ["/tools/pdf", "/guide/pdf", "/tools", "/"],
    },
    {
        "id": "spreadsheet-desk-work",
        "enabled": True,
        "category_label": "表計算・デスク作業",
        "title": "表作業を進めやすくする仕事道具",
        "query": "テンキー オフィス用品",
        "query_variants": ["デスク作業 文房具", "オフィス用品 書類整理"],
        "cta": "表作業の道具を見る",
        "priority_page_types": ["tool", "tool_index", "landing", "guide"],
        "priority_path_prefixes": ["/tools/csv", "/guide/csv", "/tools"],
    },
    {
        "id": "image-material-work",
        "enabled": True,
        "category_label": "画像・資料作成",
        "title": "画像整理・資料作成に役立つ仕事道具",
        "query": "資料作成 文房具",
        "query_variants": ["画像編集 Kindle", "撮影 小物 仕事道具"],
        "cta": "資料作成の道具を見る",
        "priority_page_types": ["tool", "tool_index", "landing", "guide"],
        "priority_path_prefixes": ["/tools/image-batch", "/tools/image-cleanup", "/guide/image", "/tools"],
    },
    {
        "id": "desk-organization",
        "enabled": True,
        "category_label": "デスク整理",
        "title": "デスクまわりを整える仕事道具",
        "query": "デスク整理 収納",
        "query_variants": ["ケーブル収納 デスク", "文房具 ファイル整理"],
        "cta": "デスク整理を見る",
        "priority_page_types": ["landing", "tool_index", "tool", "contact", "generic"],
        "priority_path_prefixes": ["/", "/tools", "/contact"],
    },
    {
        "id": "office-stationery",
        "enabled": True,
        "category_label": "文房具・オフィス用品",
        "title": "毎日の作業に使う文房具・オフィス用品",
        "query": "文房具 オフィス用品",
        "query_variants": ["ファイル整理 文房具", "書類整理 オフィス用品"],
        "cta": "文房具を見る",
        "priority_page_types": ["landing", "tool_index", "tool", "info"],
        "priority_path_prefixes": ["/", "/tools", "/faq"],
    },
    {
        "id": "desk-focus-environment",
        "enabled": True,
        "category_label": "作業環境",
        "title": "集中しやすいデスク環境をつくる道具",
        "query": "デスク環境 集中",
        "query_variants": ["姿勢 デスクワーク", "作業環境 グッズ"],
        "cta": "作業環境を見る",
        "priority_page_types": ["landing", "tool_index", "guide", "info"],
        "priority_path_prefixes": ["/", "/tools", "/guide", "/about"],
    },
]

AMAZON_PURPOSE_GENRES = AMAZON_THEME_POOL

PATH_KEYWORD_RULES: List[Tuple[str, List[str]]] = [
    ("/tools/pdf", ["Kindle PDF 仕事効率化", "PDF 書類整理 文房具", "デスク整理 収納"]),
    ("/guide/pdf", ["Kindle PDF 仕事効率化", "書類整理 文房具", "ビジネス文書 Kindle"]),
    ("/tools/csv", ["Kindle Excel", "Kindle データ分析", "テンキー オフィス用品"]),
    ("/guide/csv", ["Kindle Excel", "Excel 表計算 Kindle", "デスク作業 文房具"]),
    ("/tools/image-cleanup", ["Kindle 画像編集", "撮影 小物 仕事道具", "資料作成 文房具"]),
    ("/tools/image-batch", ["Kindle 画像編集", "資料作成 Kindle", "画像整理 文房具"]),
    ("/guide/image", ["Kindle 画像編集", "資料作成 Kindle", "撮影 小物 仕事道具"]),
    ("/tools/seo", ["Kindle SEO", "Kindle Webマーケティング", "SNS運用 Kindle"]),
    ("/guide/seo", ["Kindle SEO", "Kindle Webマーケティング", "文章術 Kindle"]),
    ("/tools", ["Kindle 仕事効率化", "Kindle Excel", "Kindle SEO", "デスク整理 文房具"]),
    ("/blog", ["Kindle Excel", "Kindle 仕事効率化", "文章術 Kindle"]),
    ("/guide", ["Kindle 仕事効率化", "資料作成 Kindle", "デスク整理 収納"]),
    ("/faq", ["Kindle 仕事効率化", "文房具 オフィス用品", "デスク整理 収納"]),
    ("/glossary", ["Kindle 仕事効率化", "Kindle Excel", "Kindle SEO"]),
    ("/contact", ["デスク整理 収納", "文房具 オフィス用品", "Kindle 仕事効率化"]),
]

PAGE_TYPE_KEYWORDS: Dict[str, List[str]] = {
    "landing": ["Kindle 仕事効率化", "Kindle Excel", "Kindle SEO", "デスク整理 文房具"],
    "guide": ["Kindle 仕事効率化", "資料作成 Kindle", "文房具 オフィス用品"],
    "tool": ["Kindle Excel", "Kindle SEO", "PDF 書類整理 文房具"],
    "tool_index": ["Kindle 仕事効率化", "Kindle Excel", "Kindle SEO", "デスク整理 文房具"],
    "article": ["Kindle Excel", "Kindle 仕事効率化", "文章術 Kindle"],
    "blog_index": ["Kindle 仕事効率化", "Kindle Excel", "文章術 Kindle"],
    "case_index": ["Kindle 仕事効率化", "デスク整理 文房具", "資料作成 Kindle"],
    "info": ["Kindle 仕事効率化", "文房具 オフィス用品", "デスク整理 収納"],
    "trust_sensitive": ["Kindle 仕事効率化", "文房具 オフィス用品", "デスク整理 収納"],
    "legal": ["Kindle 仕事効率化", "文房具 オフィス用品"],
    "contact": ["文房具 オフィス用品", "デスク整理 収納"],
    "generic": ["Kindle 仕事効率化", "デスク整理 収納", "文房具 オフィス用品"],
}
