# -*- coding: utf-8 -*-
"""Public tool catalog for しごと道具箱."""

PUBLIC_TOOL_IDS = ('pdf', 'csv', 'image-batch', 'image-compress', 'qr-code', 'image-cleanup', 'seo')

PRODUCTS = [
    {
        'id': 'pdf',
        'summary': 'PDFの結合・抽出・分割・ページ削除・回転・圧縮と、PDFと画像の相互変換ができます。処理結果はPDF、画像、ZIPで保存できます。',
        'inputs': ['PDF', 'PNG', 'JPEG', 'WebP'],
        'outputs': ['PDF', 'PNG', 'JPEG', 'ZIP'],
        'processing_location': '保護付与はサーバー処理、その他の操作はブラウザ内処理。',
        'limitations_source': 'templates/tools/pdf.html',
        'name': 'PDFツール',
        'description': 'PDFの結合、抽出、分割、ページ削除、回転、圧縮、画像変換、保護付与をまとめて扱えます。',
        'path': '/tools/pdf',
        'guide_path': '/guide/pdf',
        'status': 'available',
        'icon': 'PDF',
        'category': '書類',
        'tags': ['PDF', '書類'],
        'features': ['結合', '抽出', '分割', 'ページ削除', 'ページ回転', '圧縮', '画像変換', '保護付与'],
    },
    {
        'id': 'csv',
        'summary': 'CSVとXLSXを変換し、文字コード確認・重複削除・列整理・行数ごとの分割ができます。ブラウザ内で処理し、CSV・XLSXまたはZIPで保存できます。',
        'inputs': ['CSV', 'XLSX'],
        'outputs': ['CSV', 'XLSX', 'ZIP'],
        'processing_location': 'ブラウザ内処理。ファイル内容をサーバーへ送信しません。',
        'limitations_source': 'templates/tools/csv.html',
        'name': 'CSV/Excelツール',
        'description': 'CSVとXLSXの変換、文字コード確認、重複削除、列整理をブラウザで進められます。',
        'path': '/tools/csv',
        'guide_path': '/guide/csv',
        'status': 'available',
        'icon': 'CSV',
        'category': '表',
        'tags': ['CSV', 'Excel', '表'],
        'features': ['CSV/XLSX変換', '文字コード確認', '重複削除', '列整理'],
    },
    {
        'id': 'image-batch',
        'summary': 'JPEG・PNG・WebPを一括変換・リサイズし、画像またはZIPで保存できます。静止GIF・BMP・AVIFの入力とAVIF出力は対応ブラウザで利用できます。',
        'inputs': ['JPEG', 'PNG', 'WebP', '静止GIF・BMP・AVIF（ブラウザ依存）'],
        'outputs': ['JPEG', 'PNG', 'WebP', 'AVIF（ブラウザ依存）', 'ZIP'],
        'processing_location': 'ブラウザ内処理。画像をサーバーへ送信しません。',
        'limitations_source': 'templates/tools/image-batch.html',
        'name': '画像一括変換',
        'description': 'JPEG、PNG、WebPの形式変換と複数サイズのリサイズをブラウザ内でまとめて実行できます。',
        'path': '/tools/image-batch',
        'guide_path': '/guide/image-batch',
        'status': 'available',
        'icon': 'IMG',
        'category': '画像',
        'tags': ['画像', '変換'],
        'features': ['JPEG・PNG・WebP変換', '複数サイズ', 'リネーム', 'ZIP保存'],
    },
    {
        'id': 'image-compress',
        'summary': 'JPEG・PNG・WebP画像の品質や寸法を調整し、圧縮前後の容量を比較できます。ブラウザ内で処理し、画像またはZIPで保存できます。',
        'inputs': ['JPEG', 'PNG', 'WebP'],
        'outputs': ['JPEG', 'PNG', 'WebP', 'AVIF（ブラウザ依存）', 'ZIP'],
        'processing_location': 'ブラウザ内処理。画像をサーバーへ送信しません。',
        'limitations_source': 'templates/tools/image-compress.html',
        'name': '画像圧縮',
        'description': 'JPEG、PNG、WebPの品質やサイズを調整し、圧縮前後の容量を比較できます。',
        'path': '/tools/image-compress',
        'guide_path': '/guide/image-compress',
        'status': 'available',
        'icon': 'CMP',
        'category': '画像',
        'tags': ['画像', '圧縮', '軽量化'],
        'features': ['品質調整', 'リサイズ', '容量比較', 'ZIP保存'],
    },
    {
        'id': 'qr-code',
        'summary': 'URL、テキスト、メール、電話番号、Wi-Fi接続情報をQRコードにして、PNGまたはSVGで保存できます。',
        'inputs': ['URL', 'テキスト', 'メール', '電話番号', 'Wi-Fi接続情報'],
        'outputs': ['PNG', 'SVG'],
        'processing_location': 'ブラウザ内処理。入力内容をサーバーへ送信しません。',
        'limitations_source': 'templates/tools/qr-code.html',
        'name': 'QRコード作成',
        'description': 'URL、テキスト、メール、電話番号、Wi-Fi接続情報からQRコードをブラウザ内で作成できます。',
        'path': '/tools/qr-code',
        'guide_path': '/guide/qr-code',
        'status': 'available',
        'icon': 'QR',
        'category': '共有',
        'tags': ['QRコード', 'URL', 'Wi-Fi', '共有'],
        'features': ['URL', 'テキスト', 'メール', '電話番号', 'Wi-Fi', 'PNG・SVG保存'],
    },
    {
        'id': 'image-cleanup',
        'summary': 'PNG・JPEG・WebP画像の白背景化、余白、比率、枠を整えます。ブラウザ内で処理し、PNG・JPEG・WebPまたはZIPで保存できます。',
        'inputs': ['PNG', 'JPEG', 'WebP'],
        'outputs': ['PNG', 'JPEG', 'WebP', 'ZIP'],
        'processing_location': 'ブラウザ内処理。画像をサーバーへ送信しません。',
        'limitations_source': 'templates/tools/image-cleanup.html',
        'name': '画像クリーンアップ',
        'description': '白背景化や余白調整を行い、資料に使いやすい画像として出力できます。',
        'path': '/tools/image-cleanup',
        'guide_path': '/guide/image-cleanup',
        'status': 'available',
        'icon': 'CLR',
        'category': '画像',
        'tags': ['画像', '整える'],
        'features': ['白背景化', '余白調整', '比率調整', 'PNG・JPEG・WebP出力'],
    },
    {
        'id': 'seo',
        'summary': 'HTMLやURLからtitle・meta・OGP・canonicalを確認し、OGP画像、sitemap、robots.txtを作成できます。URLの自動収集はサーバーから同一ホスト内へ接続します。',
        'inputs': ['HTML', '公開URL', 'URL一覧', 'OGP画像の文字・画像'],
        'outputs': ['検査結果', 'PNG', 'JPEG', 'WebP', 'XML', 'テキスト'],
        'processing_location': 'HTML検査・画像生成はブラウザ内。URL入力は対象サイトへ通信し、自動収集はサーバー経由。',
        'limitations_source': 'templates/tools/seo.html',
        'name': 'SEO/URL確認',
        'description': 'title、meta、OGP、sitemap、robots.txtなど公開ページの基本情報を確認できます。',
        'path': '/tools/seo',
        'guide_path': '/guide/seo',
        'status': 'available',
        'icon': 'SEO',
        'category': 'Web確認',
        'tags': ['SEO', 'URL', 'Web確認'],
        'features': ['title確認', 'meta確認', 'OGP確認', 'sitemap確認'],
    },
]


def get_public_products():
    by_id = {p['id']: p for p in PRODUCTS if p.get('status') == 'available'}
    return [by_id[tool_id] for tool_id in PUBLIC_TOOL_IDS if tool_id in by_id]
